### ISSUE TITLE
[모델학습] `train.py`에서의 랜덤 오류

### ISSUE THREAD

**Issue by Yeonji-Lim** [DGU-Dalcom-2022/superstar-auto-notes-generator#12]
# block state 생성 부분 오류 해결

현재 랜덤한 오류가 나고 있음

**Comment by dolppe** [comment]
랜덤한 epoch 값에서 get_binary_reduced_tensors_from_level_faster 함수가 실행될 때 오류가 발생함
여러 곡의 문제가 아니며 하나의 곡만으로 실행시켜도 문제 발생

**Comment by dolppe** [comment]
리스트 타입인 block_reduced_targets_windows를 텐서 타입으로 변경하는 과정에서 차원 에러가 발생함
원래 output_length인 100이 맞춰져야 하는데 가끔 98, 97 등의 다른 차원이 사이에 껴있어서 발생하는 문제로 추정
이를 만드는 코드는 아래 코드임 

   block_reduced_targets_windows = [blocks_reduced_classes[
                                     i + time_offset + receptive_field - 1:i + time_offset + receptive_field - 1 + output_length,
                                     :] for i in indices]

결국 blocks_reduced_classes에서 indices에 적힌 인덱스부터 output_length인 100개만큼 값을 가져오는 것임
현재 문제 사항은 indeices의 값이 blocks_reduced_classes가 가진 length-100보다 더 큰 값으로 설정되기 때문임

**Comment by dolppe** [comment]
기본적인 extraced_feature를 거친 곡 => y
blocks_reduced를 거친 곡 => blocks_reduced_classes
로 표현됨

이 때 indices의 값은 이것저것 따지지만 결국 sequence_length-100만큼의 범위에서 랜덤으로 결정됨
sequence_length는 y의 곡 길이에 대한 차원을 가지고 오지만, 바로 가져오는 것이 아닌 y에 패딩을 진행한 후에 가져옴
따라서 패딩 진행되며 조금 더 길어진 y의 차원을 가져오기 때문에 blocks_reduced를 거친 데이터의 length와 달라지기 때문에 가끔 랜덤하게 오류가 나는 것임

결론 length에 대해 y == blocks_reduced_classes임 but 패딩된 y > blocks_reduced_classes임
이 때 random 값을 패딩된 y 기준으로 가져오니 blocks_reduced_classes에 비해 오버되는 값을 가져와서 문제 발생

따라서 패딩된 후의 y의 length를 가져오는 것이 아니라 패딩되기 전의 y의 length를 sequence_length에 저장하여 해결
