### ISSUE TITLE
[모델학습] `train.py`의 `torch.save` 오류

### ISSUE THREAD

**Issue by Yeonji-Lim** [DGU-Dalcom-2022/superstar-auto-notes-generator#13]
# 학습 성공시 save 오류

**Comment by dolppe** [comment]
base_model의 save_networks()에서 오류가 발생

torch.cuda.is_available()은 true인데, 컴퓨터 문제로 실제로 cuda를 사용하여 학습을 돌렸던 것은 아니라 생기는 문제일 것으로 예상됨
cuda 사용 여부에 따라 net.module().state_dict()를 저장하거나 net.cpu().state_dict()를 저장하는데, 현재 cpu쪽 데이터를 저장하도록 강제로 바꿔둔 상태

=>*****추후 코랩 등을 이용하여 cuda를 사용하면 이 또한 바꿔야할 수 있음*****
