### ISSUE TITLE
[모델학습] `training/README.md` 해석 & 정리

### ISSUE THREAD

**Issue by Yeonji-Lim** [DGU-Dalcom-2022/superstar-auto-notes-generator#5]
# 해야할 일

- 해석
- 정리
- 리뷰(설명)

**Comment by JYOOJIN** [comment]
훈련은 python3 train을 실행함으로써 이루어진다.관련 명령줄 매개 변수를 사용하여 py를 실행한다. 이러한 매개 변수는 python3 train.py --help를 실행하여 찾을 수 있으며, 사용된 데이터 집합 클래스(/dates/training/data), 모델(/models) 또는 /scripts/training/options/에서 코드에 정의된다.
 
매개 변수가 상당히 많기 때문에 표준 학습 프로세스를 실행할 수 있는 스크립트를 제공한다.
 
전체 DeepSaber 모델 학습 시  ./script_block_placement & ./script_block_selection을 실행하라.
 
# 데이터 셋 옵션

- Data_dir: 추출된 레벨/노래 데이터가 있는 디렉토리

- Dataset_name: 사용할 데이터 집합 클래스(현재 우리는 대부분 general_beat_saber을 사용하지만 2단계는 stage_2 데이터 집합을 사용한다).
 
- Binarized: {현재 주석이 존재하는지 여부}(binarized) 또는 {현재 특정 상태}(not binarized) 중 하나를 모델에 대한 대상으로 지정할지 여부입니다. 첫 번째는 block placement, 두 번째는 block selection을 위한 것

- Reduced_state:  축소된 상태 표현(1부터 number_states까지의 클래스)을 사용하여 상태를 나타낼지, 또는 각 위치에서 1부터 20까지의 클래스가 있는 크기 12의 텐서로 전체 상태를 나타낼지 여부. 두 번째는 새로운 데이터 세트로 테스트가 필요한 GAN 모델인 adv_wavenet에만 사용된다. 지금은 항상 reduced_state를 사용한다.

- Feature name: 사용할 feature type. 사용할 데이터에 대해 이 feature의 이름으로 process_songs.py를 실행해야 한다.

- Feature size: 사용할 feature size. 사용할 데이터에 대해 이 feature size로 process_songs.py를 실행해야 한다.

- Level_diff: 학습에 사용할 수준의 난이도를 쉼표로 구분한(공백 없이) 목록. 이 전에 process_songs.py로 모두 처리했어야 한다.

 
# 모델 옵션
 
일부 모델은 설정을 필요로 하지만 다른 모델은 그렇지 않습니다. 이 모델은 얼마나 일반적이게 설계되었는가에 따라 다릅니다.
 
- output_channels - general_beat_saber를 사용하는 경우 {예측할 클래스 수} + 4(특수 상태 수)로 설정해야 한다. Binarized를 사용할 때 예측할 클래스 수는 1입니다. 그렇지 않으면 reduced_state를 사용하는 경우 number_reduced_states가 됩니다(예: 2000).
 
- input_channels - general_beat_saber를 사용하는 경우 feature_size + 4(특수 상태의 수) + output_channels(concat_outputs가 설정된 경우, 자동 회귀 모델의 경우)여야 합니다. 자세한 내용은 아래 참조)
 
 
참고: 특수 상태는 PAD_STATE, START_STATE, END_STATE, EMENT_STATE이고, 이들은 /targ/constants.py에 지정된 인덱스입니다.
 
# 학습(training) 옵션
 
- experiment_name - 각 실행에 지정할 이름(폴더에 이 이름으로 checkpoint를 저장함).
 
- nepoch - 훈련할 에폭의 수입니다. "epoch"은 모든 곡을 통과하는 경로이지만 특정 windows 수(아래 설명 참조)만 사용하므로 모든 노래의 모든 부분을 통과하는 것은 아닙니다.
 
- nepoch_timeout - 학습 속도가 저하된 후 교육할 에폭의 수입니다.
 
- Batch_size
 
- print_freq – metrics를 인쇄할 반복 횟수
 
- save_message_freq - 학습된 모델을 저장할 반복 횟수
 
- continue_train - 설정된 경우 모델/실험의 최신(또는 load_iter) 체크포인트를 선택하고 거기서부터 교육을 계속합니다.
 
- load_iter - continue_train을 사용할 경우 로드할 체크포인트의 반복입니다.
 
- gpu_ids - 학습에 사용할 gpuid입니다(현재로서는 CUDA에서만 학습 가능. 최소 설정은 단일 GPU에 대해 0으로 설정하는 것입니다.)
 
- workers - 데이터를 로드하는 데 사용되는 병렬 프로세스 수(코어/RAM이 많을 경우 교육 속도를 높일 수 있음)
 
# 교육 프로세스 및 파라미터에 대한 자세한 설명
 
(general_beat_saber 데이터셋의 경우)
 
전체적으로, 우리는 point 또는 time point를 사용하여 시간이 이산화된 버전의 노래 또는 비트 세이버 레벨을 나타내는 discrete 시간 순서 내의 위치를 참조할 것이다. 한 point와 다음 point 사이의 시간은 매개 변수 step_time에 있다.
 
각 훈련 반복 시 데이터 세트의 __getitem__() 메서드가 호출된다.
 
__getitem__()은 데이터 집합에서 임의의 노래를 가져오며, 노래의 임의의 point에서 num_windows 인덱스를 샘플링한다. 그리고 그 point 각각에 대해 그 point에서 시작하여 길이가 input_length인 window를 추출한다.
 
M 윈도우의 이 "mini-mini-batch"는 모델에 단일 데이터 포인트로 전달된다. 배치 크기를 N으로 설정하면 __getitem_()에 대한 각 N개의 호출에 대해 M개의 창을 사용하고 이 두 차원을 결합하여 NM개의 실제 항목이 모델에 공급된다. 즉, 유효 배치 크기는 NM과 같다. 이것은 모델의 set_input() 메서드에서 수행된다. (모델에 필요한 경우 일부 재구성/순열도 수행할 수 있음).
 
각 입력 항목은 앞에서 언급한 대로 input_length 크기의 시퀀스이다. 시퀀스 인덱스 차원이 마지막이며, 앞에 임의 개수의 차원이 있을 수 있다. 웨이브넷 모델의 경우, 그것은 각 시점에서 노래 특징의 벡터를 포함하는 형상의 단일 차원을 가지고 있으며, 이것을 자동 회귀적으로 사용할 경우 모델이 생성한 출력과 연결될 수 있다.
 
웨이브넷 모델의 경우 매개변수 concat_outputs가 설정된 경우 수행되는 자동회귀적으로 모델을 사용할 경우 생성된 출력과 연결될 수 있는 각 시점에서 노래 기능의 벡터를 포함하는 단일 차원의 기능이 있습니다.
 
input_length는 매개 변수가 아니지만 receptive_field + output_length 1로 계산됩니다. output_length는 단일 항목에 대해 모델이 예측하기를 원하는 순차 출력 수입니다. -1은 단일 출력을 예측하기 위한 input_length이기 때문입니다(output_length=1). 모델에 따라 receptive_field를 설정해야 합니다. wavenet의 경우 모델 코드로 계산됩니다. 모델에 속성이 없으면 train.py은 1로 설정합니다.
 
Context
 
약간의 복잡함이 더 있다. 우리는 각 입력 지점에서 모델에 일부 시간적 컨텍스트를 전달하도록 선택할 수 있다. 이 작업은 time_shifts 매개변수를 사용하여 수행할 수 있습니다. 단일 입력으로 공급될 입력 지점 주위의 컨텍스트 창의 크기입니다. 예를 들어 time_shifts가 15인 경우 각 시점은 과거 7개 시점과 미래 7개 시점의 특징과 함께 제공됩니다. 기본적으로 이것은 time_shift 피쳐 벡터를 긴 피쳐 벡터로 연결하는 flat_context를 설정하지 않는 한 항목에 추가 차원을 제공한다.
 
Stage tow dataset
 
비슷하지만 몇 가지 차이점이 있습니다. TODO
# 시간 관련 옵션 요약
 

- time_offset - {모델에 대한 입력으로 제공된 마지막 point}와 {모델이 출력/표현을 생성하는 point} 사이의 point 수

- output_length - 모델에서 데이터 집합의 단일 항목에 대해 모델이 예측하기를 바라는 sequential output의 수

- num_windows - 데이터 집합 __getitem__()의 출력을 위해 곡이 샘플링되는 여러 시점 수. num_windows=0이면 __getitem__()이 창을 사용하는 대신 전체 시퀀스를 반환해야 함을 의미.

 
# 모델 변덕
 
일부 모델은 코드에서 다소 임시/모델 단위로 다루는 특수 기능을 가지고 있다.
 
웨이브넷
 
웨이브넷 모델은 자기 회귀적이어서 곡 특징과 자체 출력 모두를 입력으로 읽는다. 그러나 특정 시점에서의 출력을 예측하기 위해 과거와 미래의 곡 기능을 모두 읽지만, 과거의 출력만 읽을 수 있습니다. 이것은 노래 특징과 자동 회귀 입력에 대해 다른 time_offset, receptive_field 등을 설정함으로써 처리된다.
 
# 실험에 관한 정보
 
체크포인트가 각각 1220000과 1600000인 block_selectionion_new는 5월 29일 데모데이에서 사용한 모델이자 첫 번째 티저 영상입니다.
